version: '3.8'
services:
  contactdb:
    container_name: contact-db
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - "5001:3306"
    networks:
      - backend
  
  contactwebapi:
    container_name: contact-api
    image: contactwebapi
    build:
      context: .
      dockerfile: ContactWebApi/Dockerfile
    networks:
      - backend
    ports:
      - "5002:8080"
    environment:
      - DB_HOST=contactdb
      - DB_NAME=contact
      - DB_ROOT_PASSWORD=12345

networks:
  backend:
    
volumes:
  db-data: